import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { db } from '../firebase/firebaseApi'
import { collection, getDoc, getDocs, onSnapshot, query } from 'firebase/firestore'
import React, { useEffect, useState } from 'react'
import Event from '../components/Event'

export const getStaticProps = () => {
  
  return {
    props: {

    }
  }
}

export default function Home() {
  const [events, setEvents] = useState([])

  useEffect(() => {
    const getData = async () => {
      onSnapshot(collection(db, 'events'), (snapshot) => {
        setEvents(snapshot.docs.map((doc) => ({
          id: doc.id,
          event: doc.data()
        })))
      })


      // const q = query(collection(db, 'events'))
      // const snapshot = await getDocs(q)
      // const data = snapshot.docs.map((doc) => ({
      //   ...doc.data(), id: doc.id
      // }))
      // data.map(async (elem) => {
      //   const subQ = query(collection(db, `events/${elem.id}/birds`))
      //   const subSnapshot = await getDocs(subQ)
      //   const subData = subSnapshot.docs.map((doc) => ({
      //     ...doc.data(),
      //     id: doc.id
      //   }))
      //   console.log(subData)
      // })
    }
    
    getData()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>HVL-Eclocking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          {events.map(({id, event}) => (
            <Event key={id} eventId={id} name={event.name} location={event.location}/>
          ))}
        </div>
      </div>
    </div>
  )
}
